site_name: Millicom Digital
site_author: Ivan Prieto
pages:
- Home: 'index.md'
- Products:
    - 'Catalogo': 'catalog.md'
    - 'Amazon': 'amazon.md'
    - 'Shop': 'tigoshop.md'
    - 'Mi Tigo': 'mitigo.md'
    - 'Bot': 'bot.md'
    - 'MFS': 'mfs.md'
    - 'Mi Tigo Agent': 'mitigo-agent.md'
    - 'Distribution': 'pos.md'
    - 'Mi tigo B2B': 'tbo.md'
    - 'Tigo USA': 'usa.md'
    - 'Tigo Sports': 'sports.md'
- Enablers:
    - 'Tigo ID': 'index.md'
    - 'Payment Gateway': 'payment-gtw.md'
- Apis:
    - 'apis/Mobile Money API - Accounts.swagger.md'
    - 'apis/AppCallbackPayment Gateway.swagger.md'
    - 'apis/AppLinks.md'
    - 'apis/B2B Selfcare API.swagger.md'
    - 'apis/BSSPilot.md'
    - 'apis/Balance Management Service Api.swagger.md'
    - 'apis/CallUsageDetails.swagger.md'
    - 'apis/ConvergentPaymentAPI.swagger.md'
    - 'apis/DeezerTelco.md'
    - 'apis/Exacaster Next Best Offer API.swagger.md'
    - 'apis/Fulfillment Payment Gateway.swagger.md'
    - 'apis/GT Point Of Sale [PoS] API.swagger.md'
    - 'apis/Home Self Care API.swagger.md'
    - 'apis/Insurance API.swagger.md'
    - 'apis/Internet Usage Data.swagger.md'
    - 'apis/Mobile Money API - Accounts.swagger.md'
    - 'apis/Mobile Money API - Transactions.swagger.md'
    - 'apis/Mobile Money API.swagger.md'
    - 'apis/Mobile Self Care API.swagger.md'
    - 'apis/Modify Favorite Number Api.swagger.md'
    - 'apis/Music Freedom SV API.swagger.md'
    - 'apis/Netflix partner.md'
    - 'apis/Next Best Action-Offers.swagger.md'
    - 'apis/OpenTIGO - Billing.md'
    - 'apis/OpenTIGO - CRM.md'
    - 'apis/OpenTIGO - Common.md'
    - 'apis/OpenTIGO - Favorites.md'
    - 'apis/OpenTIGO - Lend.md'
    - 'apis/OpenTIGO - Push.md'
    - 'apis/OpenTIGO - Utils.md'
    - 'apis/OpenTigo Balance Management.md'
    - 'apis/Payment Gateway.swagger.md'
    - 'apis/Recharge Service Api.swagger.md'
    - 'apis/SMS Usage Details.swagger.md'
    - 'apis/Self Care API - DESIGN ONLY.swagger.md'
    - 'apis/Selfcare API Billing.swagger.md'
    - 'apis/Selfcare API CRM.swagger.md'
    - 'apis/Selfcare API Transactions.swagger.md'
    - 'apis/Sim Swap Events.swagger.md'
    - 'apis/SimCard management API.swagger.md'
    - 'apis/Tigo - Activation API.swagger.md'
    - 'apis/Tigo - Profiling API.swagger.md'
    - 'apis/Tigo Churn.swagger.md'
    - 'apis/Tigo MSISDN Identification API.swagger.md'
    - 'apis/Tigo Mobile PY Up-Selling Information API.swagger.md'
    - 'apis/Tigo Money HN.swagger.md'
    - 'apis/Tigo OAuth 2.0 API.swagger.md'
    - 'apis/TigoMobileProductsFulfillmentAPI.md'
    - 'apis/TigoMobileVASProductManagementAPI.md'
    - 'apis/UNE Accounts api.swagger.md'
    - 'apis/UberPOS.swagger.md'
    - 'apis/Virtual Appointemnts and Geolocation API.swagger.md'
    - 'apis/apiMobileSelfCare2.0.md'
    - 'apis/opentigosmartapps-tigoExchange.md'
    - 'apis/tigo-events-publisher-node.swagger.md'
    - 'apis/tigo_b2b_bo_billing_v2.swagger.md'
    - 'apis/tigo_b2b_bo_selfcare_crm_v2.swagger.md'
    - 'apis/tigo_b2b_co_billing_v2.swagger.md'
    - 'apis/tigo_b2b_co_selfcare_crm_v2.swagger.md'
    - 'apis/tigo_b2b_co_selfcare_transactions_v2.swagger.md'
    - 'apis/tigo_b2b_gt_selfcare_crm_v2.swagger.md'
    - 'apis/tigo_b2b_hn_billing_v2.swagger.md'
    - 'apis/tigo_co_customerSupport_v1.swagger.md'
    - 'apis/tigo_co_selfcare_crm_v1.swagger.md'
    - 'apis/tigo_crm_co_digitalDocuments_v2.swagger.md'
    - 'apis/tigo_home_sv_billing_v1.swagger.md'
    - 'apis/tigo_mobile_bo_crm_v1.swagger.md'
    - 'apis/tigo_mobile_gt_roaming_v1.swagger.md'
    - 'apis/tigo_sv_selfcare_crm_v1.swagger.md'
- Procesess:
    - 'How we work': 'processes/devBestPractices.md'
dev_addr: 127.0.0.1:8001


